ALTER TABLE "UserCard" ADD COLUMN "xp" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserCard" ADD COLUMN "level" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "UserCard" ADD COLUMN "matchesPlayed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserCard" ADD COLUMN "lastPlayedAt" TIMESTAMP(3);
